# Jekyll
name: Boiler
markdown: redcarpet
pygments: true
permalink: /:categories/:title

# App
package_name: boiler
package_version: 0.3.0

curl_installer: curl -s http://getboiler.com/install | sh
wget_installer: wget -qO- http://getboiler.com/install | sh -

# Menu
menu:
- text: About
  url: /about
- text: Guides
  url: /guides
- text: Registry
  url: http://registry.getboiler.com
- text: View on Github&nbsp;&rarr;
  url: https://github.com/nicinabox/boiler

# Analyics
gauges_id: 52d048d88bfdf733e3001f47

